Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -32,6 +32,14 @@ jobs:
             exit 0
           fi
         shell: bash
+
+      - name: Check if PR is from a fork
+        run: |
+          if [[ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
+            echo "PR is from a fork, skipping the workflow"
+            exit 78  # This exit code will skip the workflow
+          fi
+        shell: bash
       
       - name: Publish via EAS updates
         run: eas update --auto
