migliorata #233 (#251)
* Update publish.yml

* Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -24,7 +24,22 @@ jobs:
           token: ${{ env.EXPO_TOKEN }}
 
       - run: yarn install --immutable
+
+      - name: Check if Dependabot triggered this action
+        run: |
+          if [ "${{ github.actor }}" = "dependabot[bot]" ]; then
+            echo "Dependabot triggered this action. Skipping..."
+            exit 0
+          fi
+        shell: bash
+
+      - name: Check if PR is from a fork
+        run: |
+          if [[ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
+            echo "PR is from a fork, skipping the workflow"
+            exit 78  # This exit code will skip the workflow
+          fi
+        shell: bash
+      
       - name: Publish via EAS updates
-        # only if token is set
-        if: ${{ env.EXPO_TOKEN != '' }}
         run: eas update --auto
